name: MattiaC
favicon: null
layout_spectrum: 0.10262923431582749
typography_spectrum: 0.13790377415716648
title: produkt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7597731945570558
  lightness: 0.75
  saturation: 0.203897335100919
  rhythmicContrast: 0.7100415988825262
purpose: []
